### ISSUE TITLE
How do i get a dictionary object instead of a list in generate_from_frequencies

### ISSUE THREAD

**Issue by aj0271** [keyonvafa/inaugural-wordclouds#1]
Traceback (most recent call last):

File "", line 71, in 
for word,score in top_words])

File "C:\Users\RAJENDRAGHORPADE\Anaconda2\lib\site-packages\wordcloud\wordcloud.py", line 331, in fit_words
return self.generate_from_frequencies(frequencies)

File "C:\Users\RAJENDRAGHORPADE\Anaconda2\lib\site-packages\wordcloud\wordcloud.py", line 350, in generate_from_frequencies
frequencies = sorted(frequencies.items(), key=item1, reverse=True)

AttributeError: 'list' object has no attribute 'items'

**Comment by charlie012in** [comment]
hey!
Any luck on resolving this issue?
I am struggling with the same :)

Regards

**Comment by aveuiller** [comment]
Hello, 

If you still struggle with that, you can slightly change the code to build the dictionary by hand, e.g.:
```
# Sort your tfidf words
tfidf_element = tfidf[corpus[0]]
top_words = np.sort(np.array(tfidf_element, dtype = [('word',int), ('score',float)]),order='score')[::-1]

# Create the dictionary beforehand
top_words_dict = {}
for word,score in top_words:
    top_words_dict[dictionary[word]] = score 

# Use your dictionary in the WordCloud creation
wc = WordCloud(background_color="white",
               mask=my_mask,
               random_state=5,
               max_words=2000
              ).fit_words(top_words_dict)

```
